version: 2.1

jobs:
  distcheck:
    docker:
      # Use Ubuntu-based image with build essentials
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install autotools-dev gfortran libhdf5-mpi-dev

      - run:
          name: Bootstrap
          command: ./bootstrap

      - run:
          name: Configure
          command: ./configure

      ## Running distcheck only covers these details and saves time
      #- run:
      #    name: Build
      #    command: make all
      #
      #- run:
      #    name: Run tests
      #    command: make check

      - run:
          name: Distribution check
          command: make distcheck

workflows:
  version: 2
  distcheck:
    jobs:
      - distcheck
