#!/bin/bash
#################################################
#script to run esio_posix 
#created by Nicholas Malaya
#################################################
# Load all enviroment variables
#$ -V

# Project number : TG-MCA99S022
# NSF PETA APPS 
#$ -A TG-MCA99S022

# Number of processors
#Specify Parallel Environment (pe)
#$ -pe 1way 16

# place output in current directory
#$ -cwd

# Job Name
#$ -N esio

# Specify shell path
#$ -S /bin/bash

# Max Run Time
#$ -l h_rt=0:15:00

# Queue Type (qconf -sql)
#$ -q development
#

# email upon start and completion
#$ -M nick@ices.utexas.edu
#$ -m be

# merge standard out, standard error
#$ -j y

# run
#cd ~/src/esio/trunk/apps
ibrun ./esio_posix

################################
# Commands
#
# qstat -u npm7 :: display all jobs
# where npm7 is the user name
#
###############################



